openapi: 3.0.0
info:
  title: REST API Interface
  version: 1.0.0
servers:
  - url: https://76mcl5owtk.execute-api.eu-west-2.amazonaws.com/dev
paths:
  /prices-for-symbol:
    get:
      summary: Get prices for symbol
      parameters:
        - name: startEpochId
          in: query
          schema:
            type: integer
          description: Start Epoch ID
        - name: endEpochId
          in: query
          schema:
            type: integer
          description: End Epoch ID
        - name: symbol
          in: query
          schema:
            type: string
          description: Symbol
          required: true
        - name: limit
          in: query
          schema:
            type: integer
          description: Limit
        - name: offset
          in: query
          schema:
            type: integer
          description: Offset
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PriceFinalized'
  /votes-of/{voterAddress}:
    get:
      summary: Get votes of voter address
      parameters:
        - name: voterAddress
          in: path
          schema:
            type: string
          description: Address of voter
          required: true
        - name: startEpochId
          in: query
          schema:
            type: integer
          description: Start Epoch ID
        - name: endEpochId
          in: query
          schema:
            type: integer
          description: End Epoch ID
        - name: symbol
          in: query
          schema:
            type: string
          description: Symbol
        - name: limit
          in: query
          schema:
            type: integer
          description: Limit
        - name: offset
          in: query
          schema:
            type: integer
          description: Offset
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PriceRevealed'
components:
  schemas:
    PriceFinalized:
      type: object
      properties:
        epochID:
          type: string
        symbol:
          type: string
        price:
          type: string
        rewardedFTSO:
          type: boolean
        lowRewardPrice:
          type: string
        highRewardPrice:
          type: string
        finalizationType:
          type: integer
        timestamp:
          type: string
      required: [epochID, symbol, price, rewardedFTSO, lowRewardPrice, highRewardPrice, finalizationType, timestamp]
    PriceRevealed:
      type: object
      properties:
        epochID:
          type: string
        symbol:
          type: string
        voter:
          type: string
        price:
          type: string
        timestamp:
          type: string
        votePowerNat:
          type: string
        votePowerAsset:
          type: string
      required: [epochID, symbol, voter, price, timestamp, votePowerNat, votePowerAsset]

